# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-17 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_author_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=32, null=True)),
                ('avatar', models.FileField(null=True, upload_to='upload/')),
            ],
        ),
    ]
